sudo: required
language: java
jdk:
  - oraclejdk8
before_script:
  - wget http://services.gradle.org/distributions/gradle-5.0-bin.zip
  - unzip gradle-5.0-bin.zip
  - export GRADLE_HOME=$PWD/gradle-5.0
  - export PATH=$GRADLE_HOME/bin:$PATH
addons:
  sonarcloud:
    organization: awt02
    token:
      secure: "$SONAR_TOKEN"
script:
  - gradle compileJava compileTestJava
  - sonar-scanner
  - gradle check
notifications:
  email: true
